### PR TITLE
[feature] Adds minification for javascript and css files

### PR DESCRIPTION
**Pull request by jpei**
- Preserves source maps
 - Grunt watch updates more discrimiately on changes

### CODE REVIEW

**Comment by jpei** [comment]
Awkwardly, we have client as in client vs server as well as client vs admin. Calling testing the front 'frontEnd', open to suggestions.

**Comment by jpei** [comment]
And yes, grunt test and grunt build are awkwardly the same right now. Not sure how to differentiate the two.

**Comment by bryclee** [comment]
You could have:
-grunt test run purely testing tasks
-grunt build run purely building tasks
-grunt serve run build, test, concurrent
This would be nice because we could potentially have another task that does build and concurrent without test during development purposes.

**Comment by jpei** [comment]
Updated

**Comment by sperrow** [comment]
Looks good to me.

**Pull request merged**
